name: Máquina del Tiempo Total - Año Verde

on: 
  workflow_dispatch:

jobs:
  rellenar-pasado:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Configurar identidad
        run: |
          git config --global user.name "bustoschilatra-sudo"
          git config --global user.email "bustoschilatra@gmail.com"

      - name: Llenar el año completo
        run: |
          # Recorrer los 365 días del año hacia atrás
          for i in {365..1}; do
            
            # Fecha exacta de hace $i días a las 14:00
            DATE=$(date -d "$i days ago" +"%Y-%m-%d 14:00:00")
            
            # 35 commits por CADA día para saturar a verde oscuro sin descansos
            NUM_COMMITS=35
            
            echo "Pintando $DATE con $NUM_COMMITS commits..."
            
            for c in $(seq 1 $NUM_COMMITS); do
              echo "Commit: $DATE - $c" >> pasado.log
              git add pasado.log
              
              # EL TRUCO NATIVO QUE SÍ FUNCIONA:
              GIT_AUTHOR_DATE="$DATE" GIT_COMMITTER_DATE="$DATE" git commit -m "feat: core update" --quiet
            done
          done
          
      - name: Subir todo el pasado a GitHub
        run: |
          git push origin main
